configfile: "/oak/stanford/groups/smontgom/raungar/Sex/Scripts/environment_paths.yaml"

SEX_GROUPS=["bothhalf","m","f","both"]
RANDOMIZE_SEX=["","1","2","3","4","5"]
TISSUES=["Adipose_Subcutaneous","Adipose_Visceral_Omentum","Adrenal_Gland","Artery_Aorta","Artery_Coronary","Artery_Tibial",
"Bladder","Brain_Amygdala","Brain_Anterior_cingulate_cortex_BA24","Brain_Caudate_basal_ganglia","Brain_Cerebellar_Hemisphere",
"Brain_Cerebellum","Brain_Cortex","Brain_Frontal_Cortex_BA9","Brain_Hippocampus","Brain_Hypothalamus","Brain_Nucleus_accumbens_basal_ganglia",
"Brain_Putamen_basal_ganglia","Brain_Spinal_cord_cervical_c1","Brain_Substantia_nigra","Breast_Mammary_Tissue","Cells_Cultured_fibroblasts",
"Cells_EBV-transformed_lymphocytes","Cervix_Ectocervix","Cervix_Endocervix","Colon_Sigmoid","Colon_Transverse","Esophagus_Gastroesophageal_Junction",
"Esophagus_Mucosa","Esophagus_Muscularis","Fallopian_Tube","Heart_Atrial_Appendage","Heart_Left_Ventricle","Kidney_Cortex","Kidney_Medulla","Liver","Lung",
"Minor_Salivary_Gland","Muscle_Skeletal","Nerve_Tibial","Ovary","Pancreas","Pituitary","Prostate","Skin_Not_Sun_Exposed_Suprapubic","Skin_Sun_Exposed_Lower_leg",
"Small_Intestine_Terminal_Ileum","Spleen","Stomach","Testis","Thyroid","Uterus","Vagina","Whole_Blood"]

TISSUES=["Adipose_Subcutaneous"]
RANDOMIZE_SEX=["","1"]
SEX_GROUPS=["m"]

rule all:
	input: 
		expand(config["RAREDIR"]+"/preprocessing_v8eqtl{randomize_sex}/tpm_diff_file.txt",randomize_sex=RANDOMIZE_SEX),
		dynamic(config["RAREDIR"]+"/preprocessing_v8eqtl{randomize_sex}/{{tissue}}_{{sex}}/log.txt")
			# dynamic(expand(config["RAREDIR"]+"/preprocessing_v8eqtl{randomize_sex}/{{tissue}}_{{sex}}/log.txt",
			# randomize_sex=RANDOMIZE_SEX))


rule get_samples_tissues:
	input:
		RAREDIR=ancient(config["RAREDIR"]+"/preprocessing_v8eqtl/PEER_v8"),
 		GTEX_PCv8=config["GTEX_PCv8"],
		GTEX_SUBJECTSv8=config["GTEX_SUBJECTSv8"],
		GTEX_SAMPLESv8=config["GTEX_SAMPLESv8"],
		euro_file=config["RAREDIR"]+"/preprocessing_v8eqtl/gtex_2017-06-05_v8_euro_VCFids_notambiguous.txt",
		GTEX_RNAv8=config["GTEX_RNAv8"]
	params:
		map_file_prefix="gtex_2017-06-05_v8_samples_tissues.txt",
		do_tissues="F"		
	output:
		out=config["RAREDIR"]+"/preprocessing_v8eqtl/gtex_2017-06-05_v8_samples_tissues.txt"
	shell:
		""" 
		module load R
		Rscript /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/preprocess_expr.R --RAREDIR {input.RAREDIR} \
			--GTEX_PCv8 {input.GTEX_PCv8} --SUBJECTSv8 {input.GTEX_SUBJECTSv8} --SAMPLESv8 {input.GTEX_SAMPLESv8}  \
			--GTEX_RNAv8 {input.GTEX_RNAv8} --do_tissues {params.do_tissues} --map_file_prefix {output.out} --euro_file {input.euro_file}
		"""


rule split_tissues_reads:
	input: 
 		gtex=config["GTEX_RNAv8"]+"/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.gct.gz", #GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_tpm.gct.gz
		sample=config["RAREDIR"]+"/preprocessing_v8eqtl/gtex_2017-06-05_v8_samples_tissues.txt"
	params:
		end=".reads.txt",
		out=config["RAREDIR"]+"/preprocessing_v8eqtl/TPMsAndReads"
	output:
		log=config["RAREDIR"]+"/preprocessing_v8eqtl/log_of_reads.log"
	shell:
		"""
		module load python
		echo "python /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/split_expr_by_tissues.py --gtex {input.gtex} --out {params.out} --sample {input.sample} --end {params.end}" >{output.log}
		python /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/split_expr_by_tissues.py --gtex {input.gtex} --out {params.out} --sample {input.sample} --end {params.end}

		"""

rule split_tissues_tpm:
	input: 
		gtex=config["GTEX_RNAv8"]+"/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_tpm.gct.gz",
		sample=config["RAREDIR"]+"/preprocessing_v8eqtl/gtex_2017-06-05_v8_samples_tissues.txt"
	params:
		end=".tpm.txt",
		out=config["RAREDIR"]+"/preprocessing_v8eqtl/TPMsAndReads"
	output:
		log=config["RAREDIR"]+"/preprocessing_v8eqtl/log_of_tpm.log"
	shell:
		"""
		module load python
		echo " python /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/split_expr_by_tissues.py --gtex {input.gtex} --out {params.out} --sample {input.sample} --end {params.end} " > {output.log}
		python /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/split_expr_by_tissues.py --gtex {input.gtex} --out {params.out} --sample {input.sample} --end {params.end}
		"""
rule get_eqtl_genotypes:
	input:
		GTEX_WGSv8=config["GTEX_WGSv8"],
		egenes_path=config["GTEXv8"]+"/eqtl/GTEx_Analysis_v8_eQTL/"
	output:
		GTEX_WGSv8_sorted=temp(config["RAREDIR"]+"/preprocessing_v8eqtl/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased_sorted.vcf.gz"),
		out_vcf_path=config["RAREDIR"]+"/preprocessing_v8eqtl/gtex_2017-06-05_v8_genotypes_cis_eQTLs.vcf",
		out_cis_eqtl_path=config["RAREDIR"]+"/preprocessing_v8eqtl/gtex_2017-06-05_v8_genotypes_cis_eQTLs"
	params:
		out_bed_path=config["RAREDIR"]+"/preprocessing_v8eqtl/gtex_2017-06-05_v8_cis_eQTLs.bed"
	shell:
		""" 
		echo "/oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/get_eqtl_genotypes.sh \
			{input.egenes_path} {input.GTEX_WGSv8} {params.out_bed_path} \
			{output.out_vcf_path} {output.out_cis_eqtl_path} {output.GTEX_WGSv8_sorted}" 
		sh /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/get_eqtl_genotypes.sh \
			{input.egenes_path} {input.GTEX_WGSv8} {params.out_bed_path} \
			{output.out_vcf_path} {output.out_cis_eqtl_path} {output.GTEX_WGSv8_sorted} 
		"""

rule process_eqtl_genotypes:
	input:
		RAREDIR=ancient(config["RAREDIR"]),
		#inds="gtex_2017-06-05_v8_genotypes_cis_eQTLs.012.indv",
		#pos="gtex_2017-06-05_v8_genotypes_cis_eQTLs.012.pos",
		#genotype="gtex_2017-06-05_v8_genotypes_cis_eQTLs.012"
		inds=config["RAREDIR"]+"/preprocessing_v8eqtl/gtex_2017-06-05_v8_genotypes_cis_eQTLs.012.indv",
		pos=config["RAREDIR"]+"/preprocessing_v8eqtl/gtex_2017-06-05_v8_genotypes_cis_eQTLs.012.pos",
		genotype=config["RAREDIR"]+"/preprocessing_v8eqtl/gtex_2017-06-05_v8_genotypes_cis_eQTLs.012"
	output:
		out=config["RAREDIR"]+"/preprocessing_v8eqtl/gtex_2017-06-05_v8_genotypes_cis_eQTLs_012_processed.txt"
		#out="05_v8_genotypes_cis_eQTLs_012_processed.txt"
	shell:
		"""Rscript /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/process_gtex_v8_cis_eqtl_genotypes.R \
			--RAREDIR {input.RAREDIR} --inds {input.inds} --pos {input.pos} --genotype {input.genotype} --out {output.out}"""



## start changing things here
rule split_counts:
	input:
		indir=ancient(config["RAREDIR"]+"/preprocessing_v8eqtl"),
		GTEX_PCv8=config["GTEX_PCv8"],
		tpm_reads_dir=config["RAREDIR"]+"/preprocessing_v8eqtl/TPMsAndReads",
		GTEX_SUBJECTSv8=config["GTEX_SUBJECTSv8"],
		GTEX_SAMPLESv8=config["GTEX_SAMPLESv8"],
		GTEX_RNAv8=config["GTEX_RNAv8"],
		map_file=config["RAREDIR"]+"/preprocessing_v8eqtl/gtex_2017-06-05_v8_samples_tissues.txt",
		euro_file=config["RAREDIR"]+"/preprocessing_v8eqtl/gtex_2017-06-05_v8_euro_VCFids_notambiguous.txt",
		log_tpm=config["RAREDIR"]+"/preprocessing_v8eqtl/log_of_tpm.log",
		log_reads=config["RAREDIR"]+"/preprocessing_v8eqtl/log_of_reads.log"
	params:
		tpm_reads_dir=ancient(config["RAREDIR"]+"/preprocessing_v8eqtl/TPMsAndReads"),
		do_tissues="T",
		TPM_DIF_FILE=config["RAREDIR"]+"/preprocessing_v8eqtl{randomize_sex}/tpm_diff_file.txt",
		randomize_sex="{randomize_sex}"
	output:
		outfile=dynamic(config["RAREDIR"]+"/preprocessing_v8eqtl{randomize_sex}/{tissue}.log2.ztrans.{sex}.txt")
	shell:
		""" 
		module load R
		Rscript /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/preprocess_expr.R --indir {input.indir} \
			--GTEX_PCv8 {input.GTEX_PCv8} --SUBJECTSv8 {input.GTEX_SUBJECTSv8} --SAMPLESv8 {input.GTEX_SAMPLESv8} \
			--GTEX_RNAv8 {input.GTEX_RNAv8} --do_tissues {params.do_tissues} --map_file {input.map_file} \
			--TPM_DIF_FILE {params.TPM_DIF_FILE} --euro_file {input.euro_file} --tpm_reads_dir {input.tpm_reads_dir} \
			--randomize_sex {params.randomize_sex}
		"""
# def aggregate_files(wildcards):
#      checkpoint_output = checkpoints.split_counts.get(**wildcards).output[0]
#      return expand("reports/report_{i}.txt",
#                     i=glob_wildcards(os.path.join(checkpoint_output, "report_{i}.txt")).i)


rule get_peer_factors:
	input:
		infile=config["RAREDIR"]+"/preprocessing_v8eqtl{randomize_sex}/{tissue}.log2.ztrans.{sex}.txt",
	params:
		maxIterations=10000,
		boundTol=0.001,
		varTol=0.00001,
		e_pa=0.1,
		e_pb=10,
		a_pa=0.001,
		a_pb=0.1,
		tissue="{tissue}",
		outdir=config["RAREDIR"]+"/preprocessing_v8eqtl{randomize_sex}/{tissue}_{sex}"
	output:
		config["RAREDIR"]+"/preprocessing_v8eqtl{randomize_sex}/{tissue}_{sex}/log.txt"

	shell:
		"""
		nsamples=$(cat {infile} | wc -l) # this is actually n samples + 1
		if [ $nsamples -le 150 ]; then
			maxFactorsN=15
		elif [ $nsamples -le 249 ]; then
			maxFactorsN=30
		elif [ $nsamples -le 349 ]; then
			maxFactorsN=45
		else
			maxFactorsN=60
		fi

		module load R
		Rscript  /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/calculate_PEER_factors.R {input.infile} $maxFactorsN {params.maxIterations} {params.boundTol} {params.varTol {params.e_pa} {params.e_pb} {params.a_pa} {params.a_pb} {params.outdir} {params.tissue}
		"""
