configfile: "/oak/stanford/groups/smontgom/raungar/Sex/Scripts/environment_paths.yaml"

GROUPS=["both.sex","both.regress","both","m","f"]
TYPES=["x","aut"]


rule all:
	input: 
		expand(config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_normalized_expression_subset.{type}.{group}.txt.gz",  group=GROUPS,type=TYPES)
#		#expand(config["RAREDIR"]+"/outliers_v8/gtex_2017-06-05_normalized_expression_subset.x.{group}.txt.gz",  group=GROUPS)

#first run to prepare files
rule get_samples_tissues:
	input:
		RAREDIR=config["RAREDIR"],
		GTEX_PCv8=config["GTEX_PCv8"],
		GTEX_SUBJECTSv8=config["GTEX_SUBJECTSv8"],
		GTEX_SAMPLESv8=config["GTEX_SAMPLESv8"],
		GTEX_RNAv8=config["GTEX_RNAv8"]
		
	params:
		map_file_prefix="gtex_2017-06-05_v8_samples_tissues.txt",
		do_tissues="T"		
	output:
		out=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_v8_samples_tissues.txt"
	shell:
		""" Rscript /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/preprocess_expr.R --RAREDIR {input.RAREDIR} \
			--GTEX_PCv8 {input.GTEX_PCv8} --SUBJECTSv8 {input.GTEX_SUBJECTSv8} --SAMPLESv8 {input.GTEX_SAMPLESv8} \
			--GTEX_RNAv8 {input.GTEX_RNAv8} --do_tissues {params.do_tissues} --map_file_prefix {params.map_file_prefix} """

#split these tissues up
rule split_tissues_reads:
	input: 
		gtex=config["GTEX_RNAv8"]+"/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.gct.gz",
		sample=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_v8_samples_tissues.txt"
	params:
		end=".reads.txt",
		out=config["RAREDIR"]+"/preprocessing_v8/PEER_v8"
	shell:
		"""python /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/split_expr_by_tissues.py --gtex {input.gtex} --out {params.out} --sample {input.sample} --end {params.end}"""

rule split_tissues_tpm:
	input: 
		gtex=config["GTEX_RNAv8"]+"/GTEx_Analysis_2017-06-05_v8_RSEMv1.3.0_gene_tpm.gct.gz",
		sample=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_v8_samples_tissues.txt"
	params:
		end=".tpm.txt",
		out=config["RAREDIR"]+"/preprocessing_v8/PEER_v8"
	shell:
		"""python /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/split_expr_by_tissues.py --gtex {input.gtex} --out {params.out} --sample {input.sample} --end {params.end}"""

#actually get the counts split up
rule split_counts:
	input:
		RAREDIR=config["RAREDIR"],
		GTEX_PCv8=config["GTEX_PCv8"],
		GTEX_SUBJECTSv8=config["GTEX_SUBJECTSv8"],
		GTEX_SAMPLESv8=config["GTEX_SAMPLESv8"],
		GTEX_RNAv8=config["GTEX_RNAv8"]
	params:
		map_file_prefix="gtex_2017-06-05_v8_samples_tissues.txt",
		do_tissues="T",
		TPM_DIF_FILE=config["RAREDIR"]+"/preprocessing_v8/tpm_dif_file.txt"

	shell:
		""" Rscript /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/preprocess_expr.R --RAREDIR {input.RAREDIR} \
			--GTEX_PCv8 {input.GTEX_PCv8} --SUBJECTSv8 {input.GTEX_SUBJECTSv8} --SAMPLESv8 {input.GTEX_SAMPLESv8} \
			--GTEX_RNAv8 {input.GTEX_RNAv8} --do_tissues {params.do_tissues} --map_file_prefix {params.map_file_prefix} \
			--TPM_DIF_FILE {params.TPM_DIF_FILE}"""
rule get_eqtl_genotypes:
	input:
		GTEX_WGSv8=config["GTEX_WGSv8"],
		egenes_path=config["GTEXv8"]+"/eqtl/GTEx_Analysis_v8_eQTL/"
	output:
		GTEX_WGSv8_sorted=temp(config["RAREDIR"]+"/preprocessing_v8/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased_sorted.vcf.gz"),
		out_vcf_path=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_v8_genotypes_cis_eQTLs.vcf",
		out_cis_eqtl_path=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_v8_genotypes_cis_eQTLs"
	params:
		out_bed_path=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_v8_cis_eQTLs.bed"
	shell:
		""" 
		echo "/oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/get_eqtl_genotypes.sh \
			{input.egenes_path} {input.GTEX_WGSv8} {params.out_bed_path} \
			{output.out_vcf_path} {output.out_cis_eqtl_path} {output.GTEX_WGSv8_sorted}" 
		sh /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/get_eqtl_genotypes.sh \
			{input.egenes_path} {input.GTEX_WGSv8} {params.out_bed_path} \
			{output.out_vcf_path} {output.out_cis_eqtl_path} {output.GTEX_WGSv8_sorted} 
		"""

rule process_eqtl_genotypes:
	input:
		RAREDIR=config["RAREDIR"],
		#inds="gtex_2017-06-05_v8_genotypes_cis_eQTLs.012.indv",
		#pos="gtex_2017-06-05_v8_genotypes_cis_eQTLs.012.pos",
		#genotype="gtex_2017-06-05_v8_genotypes_cis_eQTLs.012"
		inds=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_v8_genotypes_cis_eQTLs.012.indv",
		pos=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_v8_genotypes_cis_eQTLs.012.pos",
		genotype=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_v8_genotypes_cis_eQTLs.012"
	output:
		out=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_v8_genotypes_cis_eQTLs_012_processed.txt"
		#out="05_v8_genotypes_cis_eQTLs_012_processed.txt"
	shell:
		"""Rscript /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/process_gtex_v8_cis_eqtl_genotypes.R \
			--RAREDIR {input.RAREDIR} --inds {input.inds} --pos {input.pos} --genotype {input.genotype} --out {output.out}"""
rule get_peer_factors:
	input:
		RAREDIR=config["RAREDIR"],
		peerdir=config["RAREDIR"]+"/preprocessing_v8/PEER_v8",
		scriptdir="/oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing"
	shell:
		"""sh /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/calculate_PEER_factors.sh \
		{input.peerdir} {input.scriptdir}  {input.RAREDIR}"""
rule get_resids_ztrans:
	input:
		RAREDIR=config["RAREDIR"],
		peerdir=config["RAREDIR"]+"/preprocessing_v8/PEER_v8",
		scriptdir="/oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing",
		covs="/oak/stanford/groups/smontgom/raungar/Sex/Files/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze_20genotPCs.txt",
		metadata_file=config["GTEX_SUBJECTSv8"]
	params:
		gtex_v8_eqtl_dir=config["GTEXv8"]+"/eqtl/GTEx_Analysis_v8_eQTL",
		factors_type="factors",
		logfile="log.residuals.tsv",
		inclsex="F"
	shell:
		"""sbatch /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/calculate_PEER_residuals.sh \
		{input.peerdir} {input.scriptdir} {params.gtex_v8_eqtl_dir} {input.RAREDIR} {input.covs} \
		{input.metadata_file} {params.factors_type} {params.logfile} {params.inclsex}"""


rule peer_correct_sex:
	input:
		dir_peer=config["RAREDIR"]+"/preprocessing_v8/PEER_v8",
		metadata_file=config["GTEX_SUBJECTSv8"],
		script="Scripts/Preprocessing/get_residuals_peer_by_sex.R"
	params:
		outfile="factors_sexregress.tsv"
	run:
		#for file in `ls {input.dir_peer}/*both.peer*txt`
		shell("""
		for file in `ls {input.dir_peer}/*both/factors.tsv`
		do
			echo "this file: $file"
			sbatch /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/get_residuals_peer_by_sex.sh \
			{input.dir_peer} {input.metadata_file} {input.script} $file {params.outfile}; 
		done
		""")

rule get_resids_ztrans_sex:
	input:
		RAREDIR=config["RAREDIR"],
		peerdir=config["RAREDIR"]+"/preprocessing_v8/PEER_v8",
		scriptdir="/oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing",
		covs="/oak/stanford/groups/smontgom/raungar/Sex/Files/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze_20genotPCs.txt",
		metadata_file=config["GTEX_SUBJECTSv8"]
	params:
		gtex_v8_eqtl_dir=config["GTEXv8"]+"/eqtl/GTEx_Analysis_v8_eQTL",
		factors_type="factors",
		logfile="log.residuals_inclsex.tsv",
		inclsex="T"
	run:
		#"""sh /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/calculate_PEER.sh \
		shell("""
		for file in `ls {input.peerdir}/*log2*ztrans*both*txt`
		do
			sbatch /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/calculate_PEER_residuals.sh \
			{input.peerdir} {input.scriptdir} {params.gtex_v8_eqtl_dir} {input.RAREDIR} {input.covs} \
			{input.metadata_file} {params.factors_type} {params.logfile} {params.inclsex} $file
		done 
		""")

rule get_resids_ztrans_regresssex:
	input:
		RAREDIR=config["RAREDIR"],
		peerdir=config["RAREDIR"]+"/preprocessing_v8/PEER_v8",
		scriptdir="/oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing",
		covs="/oak/stanford/groups/smontgom/raungar/Sex/Files/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze_20genotPCs.txt",
		metadata_file=config["GTEX_SUBJECTSv8"]
	params:
		gtex_v8_eqtl_dir=config["GTEXv8"]+"/eqtl/GTEx_Analysis_v8_eQTL",
		factors_type="factors_sexregress",
		logfile="log.residuals_sexregress.tsv",
		inclsex="F"
	run:
		#"""sh /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/calculate_PEER.sh \
		shell("""
		for file in `ls {input.peerdir}/*log2*ztrans*both*txt`
		do
			sbatch /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/calculate_PEER_residuals.sh \
			{input.peerdir} {input.scriptdir} {params.gtex_v8_eqtl_dir} {input.RAREDIR} {input.covs} \
			{input.metadata_file} {params.factors_type} {params.logfile} {params.inclsex} $file
		done
		""")

rule get_tissue_by_individual:
	input:
		RAREDIR=config["RAREDIR"]
	shell:
		"sh /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/get_tissue_by_individual.sh {input.RAREDIR}"

rule generate_gtf:
	input:
		gtf=config["GTEX_GENES"]
	output:
		out_a=config["RAREDIR"]+"/preprocessing_v8/autosomal_proteincoding_lncrna.gtf",
		out_x=config["RAREDIR"]+"/preprocessing_v8/x_proteincoding_lncrna.gtf"
	shell:
		"sh /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/subset_gtf.sh {input.gtf} {output.out_a} {output.out_x}"
	#run:
	#	shell("""
	#		echo "{input.gtf}"
	#		less -S {input.gtf} | awk -F"[\t;]" '{if($1~/chr[0-9]{1,2}/){print $10"\t"$11}}' | sed 's/\"//g' | awk -F" " '{if($4=="protein_coding" || $4=="lincRNA"){print $2"\t"$4}}' > {output.out_a};
	#		less -S {input.gtf} | awk -F"[\t;]" '{if($1=="chrX"){print $10"\t"$11}}' | sed 's/\"//g' | awk -F" " '{if($4=="protein_coding" || $4=="lincRNA"){print $2"\t"$4}}' > {output.out_x}
	#	""")

rule gather_filter_norm_expr:
	input:
		RAREDIR=config["RAREDIR"]
	params:
		group="{group}",
		ind_file=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_individuals_all_normalized_samples_{group}.txt",
		tissue_file=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_tissue_by_ind_{group}.txt"

	output:
		outpath=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_normalized_expression_{group}.txt.gz"

	shell:
		"""python /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/gather_filter_normalized_expression.py \
			--RAREDIR {input.RAREDIR} --outpath {output} --ind_file {params.ind_file} \
			--tissue_file {params.tissue_file} --group {params.group} """

rule filter_tissues_individuals:
	input:
		RAREDIR=config["RAREDIR"],
		sample_file=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_v8_samples_tissues.txt",
		norm_expr_file=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_normalized_expression_{group}.txt.gz",
		x_gtf_file=config["RAREDIR"]+"/preprocessing_v8/x_proteincoding_lncrna.gtf",
		a_gtf_file=config["RAREDIR"]+"/preprocessing_v8/autosomal_proteincoding_lncrna.gtf"
	output:
		outfile_x=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_normalized_expression_subset_x_{group}.txt.gz",
		outfile_a=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_normalized_expression_subset_aut_{group}.txt.gz"
	params:
		my_group="{group}"
	shell:
		""" 
			Rscript /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/filter_tissues_individuals.R \
			--RAREDIR {input.RAREDIR} --sample_file {input.sample_file} --norm_expr_file {input.norm_expr_file} \
			--x_gtf_file {input.x_gtf_file} --a_gtf_file {input.a_gtf_file} \
			--outfile_x {output.outfile_x} --outfile_a {output.outfile_a} --group {params.my_group}
		"""

