####Taken from Nicole Ferraro, reformatted for snakemake -RAU
GTEXv8: "/oak/stanford/groups/smontgom/shared/GTEx/all_data/GTEx_Analysis_2017-06-05_v8/"
GTEX_WGSv8: "/oak/stanford/groups/smontgom/shared/GTEx/all_data/GTEx_Analysis_2017-06-05_v8/genotypes/WGS/variant_calls/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased.vcf.gz"
GTEX_WGSv8_flagged: "/oak/stanford/groups/smontgom/shared/GTEx/all_data/GTEx_Analysis_2017-06-05_v8/genotypes/WGS/variant_calls/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_support_files/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_flagged_donors.txt"
GTEX_RNAv8: "/oak/stanford/groups/smontgom/shared/GTEx/all_data/GTEx_Analysis_2017-06-05_v8/rna_seq"
GTEX_ASEv8: "/oak/stanford/groups/smontgom/shared/GTEx/all_data/GTEx_Analysis_2017-06-05_v8/ase/GTEx_Analysis_v8_ASE_counts_by_subject"
GTEX_SAMPLESv8: "/oak/stanford/groups/smontgom/shared/GTEx/all_data/GTEx_Analysis_2017-06-05_v8/sample_annotations/GTEx_Analysis_2017-06-05_v8_Annotations_SampleAttributesDS.txt"
GTEX_SUBJECTSv8: "/oak/stanford/groups/smontgom/shared/GTEx/all_data/GTEx_Analysis_2017-06-05_v8/sample_annotations/GTEx_Analysis_2017-06-05_v8_Annotations_SubjectPhenotypesDS.txt"
GTEX_PCv8: "/oak/stanford/groups/smontgom/shared/GTEx/all_data/GTEx_Analysis_2017-06-05_v8/genotypes/WGS/variant_calls/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_support_files/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze_20genotPCs.txt"
GTEX_GENES: "/oak/stanford/groups/smontgom/shared/GTEx/all_data/GTEx_Analysis_2017-06-05_v8/references/gencode.v26.GRCh38.genes.gtf"

## Supporting data paths
KGDIR: "/oak/stanford/groups/smontgom/shared/1KG"
CADD: "/oak/stanford/groups/smontgom/shared/CADD/whole_genome_SNVs.tsv.gz" #not sure if works
GNOMAD: "/oak/stanford/groups/smontgom/shared/datasets/gnomad"

## Results paths
#export FILESDIR=/srv/scratch/restricted/GOATs
##FILESDIR=/srv/scratch/restricted/GOATs
RAREDIR: "/oak/stanford/groups/smontgom/raungar/Sex/Output"

## Paths to annotation files used in the feature creation pipeline
#export ANNODIR=/srv/scratch/restricted/goats/features/annotations # maybe change this for future version
#export TFDIR=${ANNODIR}/TFBS_Pouya
#export STATEDIR=${ANNODIR}/epigenomicsRoadmap/hg38
#export CONSOLIDATED=/mnt/lab_data/montgomery/shared/conservation/consolidated/sorted.consolidated.annotations.bed.gz
#export KG_AF_SNPS=/srv/scratch/restricted/goats/features/variantBeds/1KG/SNPs.1kg.AF.bed.gz
#export KG_AF_INDELS=/srv/scratch/restricted/goats/features/variantBeds/1KG/indels.1kg.AF.bed.gz
#export GNOMAD_SNPS=/srv/scratch/restricted/GOATs/features_v8/gnomad/SNPs.sorted.all.INFO.gz
#export GNOMAD_INDELS=/srv/scratch/restricted/GOATs/features_v8/gnomad/indels.sorted.all.INFO.gz
#export AF_SVs=/srv/scratch/restricted/GOATs/data_v7/SVs_from_HallLab/AF_HallLabSV.bed.gz
