configfile: "/oak/stanford/groups/smontgom/raungar/Sex/Scripts/environment_paths.yaml"

ZMIN=["2.5"] #,"3"]
NPHEN_MIN=["3"]
GROUPS=["allboth"] #,"m","f","both"]
TYPES=["x"]
MAF_MIN=["0"]
MAF_MAX=["0.01"]
MAXOUTLIERS=["3"]
CADD=["0","15"]
GENEWINDOWS=["5000"]
CHRS=[i for i in range(1,23)]


rule all:
    input:
        expand(config["RAREDIR"]+"/analysis_all/VarProp/x_{collapsedTYPE}_{outlierType}_zthresh{zmin}_nphen{nphen}_{group}_{this_filt}_CADD{cadd_min}_linc_prot_maxoutliers{max_outliers}_window{genewindow}_maf{maf_min}2{maf_max}.varprops.txt.gz",
        collapsedTYPE=["collapsed"],outlierType=["outliers"],zmin=ZMIN,nphen=NPHEN_MIN,
        group=GROUPS,this_filt=["CADDtypesGQ5BlacklistRemovedALL"],cadd_min=CADD,max_outliers=MAXOUTLIERS,
        genewindow=GENEWINDOWS,maf_min=MAF_MIN,maf_max=MAF_MAX),
        expand(config["RAREDIR"]+"/analysis_all/VarProp/chr{chrNUM}_{collapsedTYPE}_{outlierType}_zthresh{zmin}_nphen{nphen}_{group}_{this_filt}_CADD{cadd_min}_linc_prot_maxoutliers{max_outliers}_window{genewindow}_maf{maf_min}2{maf_max}.varprops.txt.gz",chrNUM=CHRS,
            collapsedTYPE=["collapsed"],outlierType=["outliers"],zmin=ZMIN,nphen=NPHEN_MIN,
            group=GROUPS,this_filt=["CADDtypesALL"],cadd_min=CADD,max_outliers=MAXOUTLIERS,
            genewindow=GENEWINDOWS,maf_min=MAF_MIN,maf_max=MAF_MAX),
        expand(config["RAREDIR"]+"/analysis_all/VarProp/aut_{collapsedTYPE}_{outlierType}_zthresh{zmin}_nphen{nphen}_{group}_{this_filt}_CADD{cadd_min}_linc_prot_maxoutliers{max_outliers}_window{genewindow}_maf{maf_min}2{maf_max}.varprops.txt.gz",
        collapsedTYPE=["collapsed"],outlierType=["outliers"],zmin=ZMIN,nphen=NPHEN_MIN,
            group=GROUPS,this_filt=["CADDtypesALL"],cadd_min=CADD,max_outliers=MAXOUTLIERS,
            genewindow=GENEWINDOWS,maf_min=MAF_MIN,maf_max=MAF_MAX)


rule get_underlying_var_proportions:
    input:
        my_outlier_file=config["RAREDIR"]+"/outliers_all/OutliersFiltered/{outlierType}_noglobal_medz_zthresh{zmin}_nphen{nphen}_x_{group}_maxoutliers{max_outliers}.txt.gz",
        combined_file=config["RAREDIR"]+"/features_v8/Combined/x_all_rvs_inds_{this_filt}_linc_prot_window{genewindow}.txt.gz"
    params:
        cadd_min="{cadd_min}",
        maf_min="{maf_min}",
        chr="x",
        maf_max="{maf_max}"
    output:
        outfile=config["RAREDIR"]+"/analysis_all/VarProp/x_{collapsedTYPE}_{outlierType}_zthresh{zmin}_nphen{nphen}_{group}_{this_filt}_CADD{cadd_min}_linc_prot_maxoutliers{max_outliers}_window{genewindow}_maf{maf_min}2{maf_max}.varprops.txt.gz"
    shell:
         """
        module load R
         Rscript Scripts/Features/get_variants_under_outliers.R \
          --combined_file {input.combined_file} \
          --outlierfile {input.my_outlier_file} \
          --outfile {output.outfile} --chr {params.chr} \
          --maf_min {params.maf_min} --maf_max {params.maf_max} \
          --cadd_min {params.cadd_min} \
        """

rule get_underlying_var_proportions_aut:
    input:
        combined_file=config["RAREDIR"]+"/features_v8/Combined/chr{chrNUM}_all_rvs_inds_{this_filt}_linc_prot_window{genewindow}.txt.gz",
        my_outlier_file=config["RAREDIR"]+"/outliers_all/OutliersFiltered/{outlierType}_noglobal_medz_zthresh{zmin}_nphen{nphen}_aut_{group}_maxoutliers{max_outliers}.txt.gz"
    params:
        cadd_min="{cadd_min}",
        maf_min="{maf_min}",
        maf_max="{maf_max}",
        chr="{chrNUM}"
    resources:
        mem_mb=22000
    output:
        outfile=config["RAREDIR"]+"/analysis_all/VarProp/chr{chrNUM}_{collapsedTYPE}_{outlierType}_zthresh{zmin}_nphen{nphen}_{group}_{this_filt}_CADD{cadd_min}_linc_prot_maxoutliers{max_outliers}_window{genewindow}_maf{maf_min}2{maf_max}.varprops.txt.gz"
    shell:
        """
        module load R
         Rscript Scripts/Features/get_variants_under_outliers.R \
          --combined_file {input.combined_file} \
          --outlierfile {input.my_outlier_file} \
          --outfile {output.outfile} --chr {params.chr} \
          --maf_min {params.maf_min} --maf_max {params.maf_max} \
          --cadd_min {params.cadd_min} \
        """
rule get_underlying_var_proportions_allaut:
    input:
        infiles=expand(config["RAREDIR"]+"/analysis_all/VarProp/chr{chrNUM}_{{collapsedTYPE}}_{{outlierType}}_zthresh{{zmin}}_nphen{{nphen}}_{{group}}_{{this_filt}}_CADD{{cadd_min}}_linc_prot_maxoutliers{{max_outliers}}_window{{genewindow}}_maf{{maf_min}}2{{maf_max}}.varprops.txt.gz",chrNUM=CHRS)
    output:
        outfile=config["RAREDIR"]+"/analysis_all/VarProp/aut_{collapsedTYPE}_{outlierType}_zthresh{zmin}_nphen{nphen}_{group}_{this_filt}_CADD{cadd_min}_linc_prot_maxoutliers{max_outliers}_window{genewindow}_maf{maf_min}2{maf_max}.varprops.txt.gz"
    shell:
        """
        zcat {input} | gzip -c > {output}
        """
