configfile: "/oak/stanford/groups/smontgom/raungar/Sex/Scripts/environment_paths.yaml"


import os, glob

FILES = [ os.path.basename(x) for x in glob.glob(config["FILESDIR"]+"/SexDEGs/*csv") ]
TISSUES=  list(set([ "".join(((x.split("-")[1]).split("."))[0]) for x in FILES]))
#TISSUES="BREAST"
print(TISSUES)
CHR=["x","aut"]
MINMAF=0
MAXMAF=0.01


rule all:
	input: 
		config["RAREDIR"]+"/sexdeg_v8/all_genes_chr.txt",
		#expand(config["RAREDIR"]+"/sexdeg_v8/all_genes_sexDEGs_rvs_{tissue}.txt.gz",
		expand(config["RAREDIR"]+"/sexdeg_v8/rr_{tissue}_{minmaf}_{maxmaf}_{chr}.txt",
				tissue=TISSUES,chr=CHR,minmaf=MINMAF,maxmaf=MAXMAF),
		expand(config["RAREDIR"]+"/sexdeg_v8/all_genes_sexDEGs_rvs_{tissue}_{minmaf}_{maxmaf}.txt.gz",
				tissue=TISSUES,chr=CHR,minmaf=MINMAF,maxmaf=MAXMAF)
		#expand(config["RAREDIR"]+"/sexdeg_v8/all_genes_sexDEGs_rvs_{tissue}.txt.gz",
		#expand(config["RAREDIR"]+"/sexdeg_v8/smg_{tissue}.txt",tissue=TISSUES)

rule get_genes:
	input:
		config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_normalized_expression_gathered_both_half.regress.txt.gz"
	output:
		config["RAREDIR"]+"/sexdeg_v8/all_genes.txt"
	shell:
		"""
		less {input} | awk -F"\t" 'NR>1 {{print $2}}' | sort | uniq > {output}
		"""
rule get_chr:
	input:
		genelist=config["RAREDIR"]+"/sexdeg_v8/all_genes.txt",
		gtf=config["GTEX_GENES"],
		script=config["SCRIPTSDIR"]+"/SexDeg/gtf_to_genes_chr.py"
	output:
		outfile=config["RAREDIR"]+"/sexdeg_v8/all_genes_chr.txt"
	shell:
		"""
		python3 {input.script} --infile {input.genelist} --gtf {input.gtf} --outfile {output.outfile}
		"""

rule overlap_genes_sexdegs:
	input:
		genes=config["RAREDIR"]+"/sexdeg_v8/all_genes_chr.txt",
		sexdegs=config["FILESDIR"]+"/SexDEGs/sexDEGS-{tissue}.csv",
		myscript=config["SCRIPTSDIR"]+"/SexDeg/combine_allgenes_sexdegs.sh"
	output:
		config["RAREDIR"]+"/sexdeg_v8/all_genes_sexDEGs_{tissue}.txt"
	shell:
		"""
		#echo "DN"
		sh {input.myscript} {input.genes} {input.sexdegs} {output}
		"""

rule add_RVs:
	input:
		#rvs=config["RAREDIR"]+"/features_v8/collapsed_maf_both_x.tsv.gz",
		rvs=config["RAREDIR"]+"/features_v8/collapsed_maf_both_all.tsv.gz",
		sexdegs=config["RAREDIR"]+"/sexdeg_v8/all_genes_sexDEGs_{tissue}.txt",
		myscript=config["SCRIPTSDIR"]+"/SexDeg/intersect_sexdegs_rvs.py"
	output:
		config["RAREDIR"]+"/sexdeg_v8/all_genes_sexDEGs_rvs_{tissue}_{minmaf}_{maxmaf}.txt.gz"
	params:
		min="{minmaf}",
		max="{maxmaf}"
	log:
		config["RAREDIR"]+"/sexdeg_v8/all_genes_sexDEGs_rvs_{tissue}_{minmaf}_{maxmaf}.log"
	shell:
		"""
		python3 {input.myscript} --rvsites_file {input.rvs} \
		--genes_sexdegs {input.sexdegs} --outfile {output} \
		--logfile {log} --minmaf {params.min} --maxmaf {params.max}
		"""

rule get_frac_file:
	input: 
		rv_file=config["RAREDIR"]+"/sexdeg_v8/all_genes_sexDEGs_rvs_{tissue}_{minmaf}_{maxmaf}.txt.gz",
		script=config["SCRIPTSDIR"]+"/SexDeg/get_rr.sh"
	output:
		out_aut=config["RAREDIR"]+"/sexdeg_v8/risktable_{tissue}_{minmaf}_{maxmaf}_aut.txt",
		out_x=config["RAREDIR"]+"/sexdeg_v8/risktable_{tissue}_{minmaf}_{maxmaf}_x.txt"
	shell:
		"""
		sh {input.script} {input.rv_file} {output.out_aut} {output.out_x}
		"""
		
rule calc_risk:
	input:
		infile=config["RAREDIR"]+"/sexdeg_v8/risktable_{tissue}_{chr}_{minmaf}_{maxmaf}.txt",
		rscript=config["SCRIPTSDIR"]+"/SexDeg/get_rr_epitab.R"
	output:
		config["RAREDIR"]+"/sexdeg_v8/rr_{tissue}_{chr}_{minmaf}_{maxmaf}.txt"
	shell:
		"""
		module load R
		Rscript {input.rscript} --infile {input.infile} --outfile {output}
		"""
	
