configfile: "/oak/stanford/groups/smontgom/raungar/Sex/Scripts/environment_paths.yaml"

rule get_samples_tissues:
	input:
		RAREDIR=config["RAREDIR"],
		GTEX_PCv8=config["GTEX_PCv8"],
		GTEX_SUBJECTSv8=config["GTEX_SUBJECTSv8"],
		GTEX_SAMPLESv8=config["GTEX_SAMPLESv8"],
		GTEX_RNAv8=config["GTEX_RNAv8"]
	params:
		map_file_prefix="gtex_2017-06-05_v8_samples_tissues.txt",
		do_tissues="F"		
	output:
		out=config["RAREDIR"]+"/preprocessing_v8/gtex_2017-06-05_v8_samples_tissues.txt"
	shell:
		""" Rscript /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/preprocess_expr.R --RAREDIR {input.RAREDIR} \
			--GTEX_PCv8 {input.GTEX_PCv8} --SUBJECTSv8 {input.GTEX_SUBJECTSv8} --SAMPLESv8 {input.GTEX_SAMPLESv8} \
			--GTEX_RNAv8 {input.GTEX_RNAv8} --do_tissues {params.do_tissues} --map_file_prefix {params.map_file_prefix} """

rule split_tissues:
	input: 
		gtex=config["GTEX_RNAv8"]+"/GTEx_Analysis_2017-06-05_v8_RSEMv1.3.0_gene_tpm.gct.gz",
		sample=config["RAREDIR"]+"/Preprocessing/gtex_2017-06-05_v8_samples_tissues.txt"
	params:
		end=".tpm.txt"

	output:
		out=config["RAREDIR"]+"/Preprocessing_v8/PEER_v8"
	shell:
		"""python /oak/stanford/groups/smontgom/raungar/Sex/Scripts/Preprocessing/split_expr_by_tissues.py --gtex {input.gtex} --out {output.out} --sample {input.sample} --end {params.end}"""
